# Site
name: 'Rena Wang - Portfolio'
description: 'A collection of my projects!'
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
#avatar: 'assets/images/sal.jpg'
email: 'renaw@mit.edu'

include: ["_pages"]
permalink: pretty

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
      
# Syntax
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 20


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]